# Generated by Django 4.1.3 on 2022-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='ชื่อหัวข้อบทความ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='รายละเอียดบทความ')),
                ('author', models.CharField(max_length=255, verbose_name='ชื่อผู้แต่งบทความ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
